import {
  uuid,
  pgTable,
  integer,
  text,
  numeric,
  boolean,
  timestamp,
  check,
} from 'drizzle-orm/pg-core'
import { sql } from 'drizzle-orm'

export const settings = pgTable(
  'settings',
  {
    id: uuid('id').default('00000000-0000-0000-0000-000000000000').primaryKey(),
    gymName: text('gym_name').notNull().default('Mi Gimnasio'),
    gymAddress: text('gym_address').default(''),
    gymPhone: text('gym_phone').default(''),
    gymEmail: text('gym_email').default(''),
    taxRate: numeric('tax_rate', { precision: 5, scale: 2 }).default('0.00'),
    currencySymbol: text('currency_symbol').default('$'),
    currencyCode: text('currency_code').default('ARS'),
    decimalPlaces: integer('decimal_places').default(2),
    lowStockThreshold: integer('low_stock_threshold').default(5),
    membershipReminderDays: integer('membership_reminder_days').default(7),
    checkInWindowMinutes: integer('check_in_window_minutes').default(60),
    enableAutoRenew: boolean('enable_auto_renew').default(false),
    logoBase64: text('logo_base64'),
    resendApiKey: text('resend_api_key').default(''),
    emailFrom: text('email_from').default(''),
    // Twilio (WhatsApp + SMS)
    twilioAccountSid: text('twilio_account_sid').default(''),
    twilioAuthToken: text('twilio_auth_token').default(''),
    twilioWhatsAppNumber: text('twilio_whatsapp_number').default(''),
    twilioSmsNumber: text('twilio_sms_number').default(''),
    // WhatsApp Content Template SIDs (Twilio Content API)
    waTemplateExpirationSid: text('wa_template_expiration_sid').default(''),
    waTemplateExpiredSid: text('wa_template_expired_sid').default(''),
    waTemplateBirthdaySid: text('wa_template_birthday_sid').default(''),
    waTemplateInactiveSid: text('wa_template_inactive_sid').default(''),
    waTemplateClassReminderSid: text('wa_template_class_reminder_sid').default(''),
    // Firebase Cloud Messaging config
    firebaseApiKey: text('firebase_api_key').default(''),
    firebaseAuthDomain: text('firebase_auth_domain').default(''),
    firebaseProjectId: text('firebase_project_id').default(''),
    firebaseMessagingSenderId: text('firebase_messaging_sender_id').default(''),
    firebaseAppId: text('firebase_app_id').default(''),
    firebaseVapidKey: text('firebase_vapid_key').default(''),
    firebaseServiceAccount: text('firebase_service_account').default(''),
    // Fiscal data for invoices
    companyTaxId: text('company_tax_id').default(''),
    companyLegalName: text('company_legal_name').default(''),
    invoiceFooter: text('invoice_footer').default(''),
    autoRenewSecretKey: text('auto_renew_secret_key').default(''),
    // Stripe (Cobro automático con tarjeta)
    stripeSecretKey: text('stripe_secret_key').default(''),
    stripePublishableKey: text('stripe_publishable_key').default(''),
    stripeWebhookSecret: text('stripe_webhook_secret').default(''),
    backupEnabled: boolean('backup_enabled').default(false),
    backupFrequency: text('backup_frequency').default('weekly'),
    openingTime: text('opening_time').default('08:00'),
    closingTime: text('closing_time').default('22:00'),
    mondayOpen: boolean('monday_open').default(true),
    tuesdayOpen: boolean('tuesday_open').default(true),
    wednesdayOpen: boolean('wednesday_open').default(true),
    thursdayOpen: boolean('thursday_open').default(true),
    fridayOpen: boolean('friday_open').default(true),
    saturdayOpen: boolean('saturday_open').default(false),
    sundayOpen: boolean('sunday_open').default(false),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
  },
  (table) => [
    check(
      'settings_single_row',
      sql`${table.id} = '00000000-0000-0000-0000-000000000000'::uuid`,
    ),
  ],
)
