/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QrCheckinRouteImport } from './routes/qr-checkin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedTrainersRouteImport } from './routes/_authed/trainers'
import { Route as AuthedSuppliersRouteImport } from './routes/_authed/suppliers'
import { Route as AuthedSubscriptionsRouteImport } from './routes/_authed/subscriptions'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedSalesRouteImport } from './routes/_authed/sales'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthedRenewalsRouteImport } from './routes/_authed/renewals'
import { Route as AuthedQrCodesRouteImport } from './routes/_authed/qr-codes'
import { Route as AuthedPurchasesRouteImport } from './routes/_authed/purchases'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedProductsRouteImport } from './routes/_authed/products'
import { Route as AuthedProductCategoriesRouteImport } from './routes/_authed/product-categories'
import { Route as AuthedPosRouteImport } from './routes/_authed/pos'
import { Route as AuthedPackagesRouteImport } from './routes/_authed/packages'
import { Route as AuthedNotificationsRouteImport } from './routes/_authed/notifications'
import { Route as AuthedMembershipPaymentsRouteImport } from './routes/_authed/membership-payments'
import { Route as AuthedMembershipFreezesRouteImport } from './routes/_authed/membership-freezes'
import { Route as AuthedMembersRouteImport } from './routes/_authed/members'
import { Route as AuthedInventoryRouteImport } from './routes/_authed/inventory'
import { Route as AuthedExportRouteImport } from './routes/_authed/export'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedClassesRouteImport } from './routes/_authed/classes'
import { Route as AuthedCheckInsRouteImport } from './routes/_authed/check-ins'
import { Route as AuthedCashRegisterRouteImport } from './routes/_authed/cash-register'
import { Route as AuthedBranchesRouteImport } from './routes/_authed/branches'
import { Route as AuthedBackupRouteImport } from './routes/_authed/backup'
import { Route as AuthedAuditLogsRouteImport } from './routes/_authed/audit-logs'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'

const QrCheckinRoute = QrCheckinRouteImport.update({
  id: '/qr-checkin',
  path: '/qr-checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTrainersRoute = AuthedTrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSuppliersRoute = AuthedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSubscriptionsRoute = AuthedSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSalesRoute = AuthedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRenewalsRoute = AuthedRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedQrCodesRoute = AuthedQrCodesRouteImport.update({
  id: '/qr-codes',
  path: '/qr-codes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPurchasesRoute = AuthedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsRoute = AuthedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductCategoriesRoute = AuthedProductCategoriesRouteImport.update({
  id: '/product-categories',
  path: '/product-categories',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPosRoute = AuthedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPackagesRoute = AuthedPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotificationsRoute = AuthedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMembershipPaymentsRoute =
  AuthedMembershipPaymentsRouteImport.update({
    id: '/membership-payments',
    path: '/membership-payments',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedMembershipFreezesRoute = AuthedMembershipFreezesRouteImport.update({
  id: '/membership-freezes',
  path: '/membership-freezes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMembersRoute = AuthedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInventoryRoute = AuthedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedExportRoute = AuthedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClassesRoute = AuthedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCheckInsRoute = AuthedCheckInsRouteImport.update({
  id: '/check-ins',
  path: '/check-ins',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCashRegisterRoute = AuthedCashRegisterRouteImport.update({
  id: '/cash-register',
  path: '/cash-register',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBranchesRoute = AuthedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBackupRoute = AuthedBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditLogsRoute = AuthedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/qr-checkin': typeof QrCheckinRoute
  '/audit-logs': typeof AuthedAuditLogsRoute
  '/backup': typeof AuthedBackupRoute
  '/branches': typeof AuthedBranchesRoute
  '/cash-register': typeof AuthedCashRegisterRoute
  '/check-ins': typeof AuthedCheckInsRoute
  '/classes': typeof AuthedClassesRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/export': typeof AuthedExportRoute
  '/inventory': typeof AuthedInventoryRoute
  '/members': typeof AuthedMembersRoute
  '/membership-freezes': typeof AuthedMembershipFreezesRoute
  '/membership-payments': typeof AuthedMembershipPaymentsRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/packages': typeof AuthedPackagesRoute
  '/pos': typeof AuthedPosRoute
  '/product-categories': typeof AuthedProductCategoriesRoute
  '/products': typeof AuthedProductsRoute
  '/profile': typeof AuthedProfileRoute
  '/purchases': typeof AuthedPurchasesRoute
  '/qr-codes': typeof AuthedQrCodesRoute
  '/renewals': typeof AuthedRenewalsRoute
  '/reports': typeof AuthedReportsRoute
  '/sales': typeof AuthedSalesRoute
  '/settings': typeof AuthedSettingsRoute
  '/subscriptions': typeof AuthedSubscriptionsRoute
  '/suppliers': typeof AuthedSuppliersRoute
  '/trainers': typeof AuthedTrainersRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/qr-checkin': typeof QrCheckinRoute
  '/audit-logs': typeof AuthedAuditLogsRoute
  '/backup': typeof AuthedBackupRoute
  '/branches': typeof AuthedBranchesRoute
  '/cash-register': typeof AuthedCashRegisterRoute
  '/check-ins': typeof AuthedCheckInsRoute
  '/classes': typeof AuthedClassesRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/export': typeof AuthedExportRoute
  '/inventory': typeof AuthedInventoryRoute
  '/members': typeof AuthedMembersRoute
  '/membership-freezes': typeof AuthedMembershipFreezesRoute
  '/membership-payments': typeof AuthedMembershipPaymentsRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/packages': typeof AuthedPackagesRoute
  '/pos': typeof AuthedPosRoute
  '/product-categories': typeof AuthedProductCategoriesRoute
  '/products': typeof AuthedProductsRoute
  '/profile': typeof AuthedProfileRoute
  '/purchases': typeof AuthedPurchasesRoute
  '/qr-codes': typeof AuthedQrCodesRoute
  '/renewals': typeof AuthedRenewalsRoute
  '/reports': typeof AuthedReportsRoute
  '/sales': typeof AuthedSalesRoute
  '/settings': typeof AuthedSettingsRoute
  '/subscriptions': typeof AuthedSubscriptionsRoute
  '/suppliers': typeof AuthedSuppliersRoute
  '/trainers': typeof AuthedTrainersRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/qr-checkin': typeof QrCheckinRoute
  '/_authed/audit-logs': typeof AuthedAuditLogsRoute
  '/_authed/backup': typeof AuthedBackupRoute
  '/_authed/branches': typeof AuthedBranchesRoute
  '/_authed/cash-register': typeof AuthedCashRegisterRoute
  '/_authed/check-ins': typeof AuthedCheckInsRoute
  '/_authed/classes': typeof AuthedClassesRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/export': typeof AuthedExportRoute
  '/_authed/inventory': typeof AuthedInventoryRoute
  '/_authed/members': typeof AuthedMembersRoute
  '/_authed/membership-freezes': typeof AuthedMembershipFreezesRoute
  '/_authed/membership-payments': typeof AuthedMembershipPaymentsRoute
  '/_authed/notifications': typeof AuthedNotificationsRoute
  '/_authed/packages': typeof AuthedPackagesRoute
  '/_authed/pos': typeof AuthedPosRoute
  '/_authed/product-categories': typeof AuthedProductCategoriesRoute
  '/_authed/products': typeof AuthedProductsRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/purchases': typeof AuthedPurchasesRoute
  '/_authed/qr-codes': typeof AuthedQrCodesRoute
  '/_authed/renewals': typeof AuthedRenewalsRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/sales': typeof AuthedSalesRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/subscriptions': typeof AuthedSubscriptionsRoute
  '/_authed/suppliers': typeof AuthedSuppliersRoute
  '/_authed/trainers': typeof AuthedTrainersRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/qr-checkin'
    | '/audit-logs'
    | '/backup'
    | '/branches'
    | '/cash-register'
    | '/check-ins'
    | '/classes'
    | '/dashboard'
    | '/export'
    | '/inventory'
    | '/members'
    | '/membership-freezes'
    | '/membership-payments'
    | '/notifications'
    | '/packages'
    | '/pos'
    | '/product-categories'
    | '/products'
    | '/profile'
    | '/purchases'
    | '/qr-codes'
    | '/renewals'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/subscriptions'
    | '/suppliers'
    | '/trainers'
    | '/admin/users'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/qr-checkin'
    | '/audit-logs'
    | '/backup'
    | '/branches'
    | '/cash-register'
    | '/check-ins'
    | '/classes'
    | '/dashboard'
    | '/export'
    | '/inventory'
    | '/members'
    | '/membership-freezes'
    | '/membership-payments'
    | '/notifications'
    | '/packages'
    | '/pos'
    | '/product-categories'
    | '/products'
    | '/profile'
    | '/purchases'
    | '/qr-codes'
    | '/renewals'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/subscriptions'
    | '/suppliers'
    | '/trainers'
    | '/admin/users'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/qr-checkin'
    | '/_authed/audit-logs'
    | '/_authed/backup'
    | '/_authed/branches'
    | '/_authed/cash-register'
    | '/_authed/check-ins'
    | '/_authed/classes'
    | '/_authed/dashboard'
    | '/_authed/export'
    | '/_authed/inventory'
    | '/_authed/members'
    | '/_authed/membership-freezes'
    | '/_authed/membership-payments'
    | '/_authed/notifications'
    | '/_authed/packages'
    | '/_authed/pos'
    | '/_authed/product-categories'
    | '/_authed/products'
    | '/_authed/profile'
    | '/_authed/purchases'
    | '/_authed/qr-codes'
    | '/_authed/renewals'
    | '/_authed/reports'
    | '/_authed/sales'
    | '/_authed/settings'
    | '/_authed/subscriptions'
    | '/_authed/suppliers'
    | '/_authed/trainers'
    | '/_authed/admin/users'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  QrCheckinRoute: typeof QrCheckinRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/qr-checkin': {
      id: '/qr-checkin'
      path: '/qr-checkin'
      fullPath: '/qr-checkin'
      preLoaderRoute: typeof QrCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/trainers': {
      id: '/_authed/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof AuthedTrainersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/suppliers': {
      id: '/_authed/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthedSuppliersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/subscriptions': {
      id: '/_authed/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthedSubscriptionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sales': {
      id: '/_authed/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthedSalesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/renewals': {
      id: '/_authed/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof AuthedRenewalsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/qr-codes': {
      id: '/_authed/qr-codes'
      path: '/qr-codes'
      fullPath: '/qr-codes'
      preLoaderRoute: typeof AuthedQrCodesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/purchases': {
      id: '/_authed/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthedPurchasesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products': {
      id: '/_authed/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthedProductsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/product-categories': {
      id: '/_authed/product-categories'
      path: '/product-categories'
      fullPath: '/product-categories'
      preLoaderRoute: typeof AuthedProductCategoriesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pos': {
      id: '/_authed/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthedPosRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/packages': {
      id: '/_authed/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AuthedPackagesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notifications': {
      id: '/_authed/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedNotificationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/membership-payments': {
      id: '/_authed/membership-payments'
      path: '/membership-payments'
      fullPath: '/membership-payments'
      preLoaderRoute: typeof AuthedMembershipPaymentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/membership-freezes': {
      id: '/_authed/membership-freezes'
      path: '/membership-freezes'
      fullPath: '/membership-freezes'
      preLoaderRoute: typeof AuthedMembershipFreezesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/members': {
      id: '/_authed/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthedMembersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inventory': {
      id: '/_authed/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthedInventoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/export': {
      id: '/_authed/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthedExportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/classes': {
      id: '/_authed/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthedClassesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/check-ins': {
      id: '/_authed/check-ins'
      path: '/check-ins'
      fullPath: '/check-ins'
      preLoaderRoute: typeof AuthedCheckInsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cash-register': {
      id: '/_authed/cash-register'
      path: '/cash-register'
      fullPath: '/cash-register'
      preLoaderRoute: typeof AuthedCashRegisterRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/branches': {
      id: '/_authed/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthedBranchesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/backup': {
      id: '/_authed/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AuthedBackupRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit-logs': {
      id: '/_authed/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthedAuditLogsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAuditLogsRoute: typeof AuthedAuditLogsRoute
  AuthedBackupRoute: typeof AuthedBackupRoute
  AuthedBranchesRoute: typeof AuthedBranchesRoute
  AuthedCashRegisterRoute: typeof AuthedCashRegisterRoute
  AuthedCheckInsRoute: typeof AuthedCheckInsRoute
  AuthedClassesRoute: typeof AuthedClassesRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedExportRoute: typeof AuthedExportRoute
  AuthedInventoryRoute: typeof AuthedInventoryRoute
  AuthedMembersRoute: typeof AuthedMembersRoute
  AuthedMembershipFreezesRoute: typeof AuthedMembershipFreezesRoute
  AuthedMembershipPaymentsRoute: typeof AuthedMembershipPaymentsRoute
  AuthedNotificationsRoute: typeof AuthedNotificationsRoute
  AuthedPackagesRoute: typeof AuthedPackagesRoute
  AuthedPosRoute: typeof AuthedPosRoute
  AuthedProductCategoriesRoute: typeof AuthedProductCategoriesRoute
  AuthedProductsRoute: typeof AuthedProductsRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedPurchasesRoute: typeof AuthedPurchasesRoute
  AuthedQrCodesRoute: typeof AuthedQrCodesRoute
  AuthedRenewalsRoute: typeof AuthedRenewalsRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedSalesRoute: typeof AuthedSalesRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedSubscriptionsRoute: typeof AuthedSubscriptionsRoute
  AuthedSuppliersRoute: typeof AuthedSuppliersRoute
  AuthedTrainersRoute: typeof AuthedTrainersRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAuditLogsRoute: AuthedAuditLogsRoute,
  AuthedBackupRoute: AuthedBackupRoute,
  AuthedBranchesRoute: AuthedBranchesRoute,
  AuthedCashRegisterRoute: AuthedCashRegisterRoute,
  AuthedCheckInsRoute: AuthedCheckInsRoute,
  AuthedClassesRoute: AuthedClassesRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedExportRoute: AuthedExportRoute,
  AuthedInventoryRoute: AuthedInventoryRoute,
  AuthedMembersRoute: AuthedMembersRoute,
  AuthedMembershipFreezesRoute: AuthedMembershipFreezesRoute,
  AuthedMembershipPaymentsRoute: AuthedMembershipPaymentsRoute,
  AuthedNotificationsRoute: AuthedNotificationsRoute,
  AuthedPackagesRoute: AuthedPackagesRoute,
  AuthedPosRoute: AuthedPosRoute,
  AuthedProductCategoriesRoute: AuthedProductCategoriesRoute,
  AuthedProductsRoute: AuthedProductsRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedPurchasesRoute: AuthedPurchasesRoute,
  AuthedQrCodesRoute: AuthedQrCodesRoute,
  AuthedRenewalsRoute: AuthedRenewalsRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedSalesRoute: AuthedSalesRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedSubscriptionsRoute: AuthedSubscriptionsRoute,
  AuthedSuppliersRoute: AuthedSuppliersRoute,
  AuthedTrainersRoute: AuthedTrainersRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  QrCheckinRoute: QrCheckinRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
