/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvRouteImport } from './routes/tv'
import { Route as QrCheckinRouteImport } from './routes/qr-checkin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'
import { Route as AuthedTrainersRouteImport } from './routes/_authed/trainers'
import { Route as AuthedSuppliersRouteImport } from './routes/_authed/suppliers'
import { Route as AuthedSubscriptionsRouteImport } from './routes/_authed/subscriptions'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedSalesRouteImport } from './routes/_authed/sales'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthedRenewalsRouteImport } from './routes/_authed/renewals'
import { Route as AuthedQrCodesRouteImport } from './routes/_authed/qr-codes'
import { Route as AuthedPurchasesRouteImport } from './routes/_authed/purchases'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedProductsRouteImport } from './routes/_authed/products'
import { Route as AuthedProductCategoriesRouteImport } from './routes/_authed/product-categories'
import { Route as AuthedPosRouteImport } from './routes/_authed/pos'
import { Route as AuthedPayrollRouteImport } from './routes/_authed/payroll'
import { Route as AuthedPackagesRouteImport } from './routes/_authed/packages'
import { Route as AuthedNutritionRouteImport } from './routes/_authed/nutrition'
import { Route as AuthedNotificationsRouteImport } from './routes/_authed/notifications'
import { Route as AuthedMembershipPaymentsRouteImport } from './routes/_authed/membership-payments'
import { Route as AuthedMembershipFreezesRouteImport } from './routes/_authed/membership-freezes'
import { Route as AuthedMembersRouteImport } from './routes/_authed/members'
import { Route as AuthedInvoicesRouteImport } from './routes/_authed/invoices'
import { Route as AuthedInventoryRouteImport } from './routes/_authed/inventory'
import { Route as AuthedExportRouteImport } from './routes/_authed/export'
import { Route as AuthedEmployeesRouteImport } from './routes/_authed/employees'
import { Route as AuthedEmployeeVacationsRouteImport } from './routes/_authed/employee-vacations'
import { Route as AuthedEmployeeSchedulesRouteImport } from './routes/_authed/employee-schedules'
import { Route as AuthedEmployeeAttendanceRouteImport } from './routes/_authed/employee-attendance'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedCorporateAccountsRouteImport } from './routes/_authed/corporate-accounts'
import { Route as AuthedClassesRouteImport } from './routes/_authed/classes'
import { Route as AuthedCheckInsRouteImport } from './routes/_authed/check-ins'
import { Route as AuthedCashRegisterRouteImport } from './routes/_authed/cash-register'
import { Route as AuthedBranchesRouteImport } from './routes/_authed/branches'
import { Route as AuthedBackupRouteImport } from './routes/_authed/backup'
import { Route as AuthedAuditLogsRouteImport } from './routes/_authed/audit-logs'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiCronAutoRenewalsRouteImport } from './routes/api/cron/auto-renewals'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'

const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCheckinRoute = QrCheckinRouteImport.update({
  id: '/qr-checkin',
  path: '/qr-checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTrainersRoute = AuthedTrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSuppliersRoute = AuthedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSubscriptionsRoute = AuthedSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSalesRoute = AuthedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRenewalsRoute = AuthedRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedQrCodesRoute = AuthedQrCodesRouteImport.update({
  id: '/qr-codes',
  path: '/qr-codes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPurchasesRoute = AuthedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsRoute = AuthedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductCategoriesRoute = AuthedProductCategoriesRouteImport.update({
  id: '/product-categories',
  path: '/product-categories',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPosRoute = AuthedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPayrollRoute = AuthedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPackagesRoute = AuthedPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNutritionRoute = AuthedNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotificationsRoute = AuthedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMembershipPaymentsRoute =
  AuthedMembershipPaymentsRouteImport.update({
    id: '/membership-payments',
    path: '/membership-payments',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedMembershipFreezesRoute = AuthedMembershipFreezesRouteImport.update({
  id: '/membership-freezes',
  path: '/membership-freezes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMembersRoute = AuthedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInvoicesRoute = AuthedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInventoryRoute = AuthedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedExportRoute = AuthedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEmployeesRoute = AuthedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEmployeeVacationsRoute = AuthedEmployeeVacationsRouteImport.update({
  id: '/employee-vacations',
  path: '/employee-vacations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEmployeeSchedulesRoute = AuthedEmployeeSchedulesRouteImport.update({
  id: '/employee-schedules',
  path: '/employee-schedules',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEmployeeAttendanceRoute =
  AuthedEmployeeAttendanceRouteImport.update({
    id: '/employee-attendance',
    path: '/employee-attendance',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCorporateAccountsRoute = AuthedCorporateAccountsRouteImport.update({
  id: '/corporate-accounts',
  path: '/corporate-accounts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClassesRoute = AuthedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCheckInsRoute = AuthedCheckInsRouteImport.update({
  id: '/check-ins',
  path: '/check-ins',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCashRegisterRoute = AuthedCashRegisterRouteImport.update({
  id: '/cash-register',
  path: '/cash-register',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBranchesRoute = AuthedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBackupRoute = AuthedBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditLogsRoute = AuthedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronAutoRenewalsRoute = ApiCronAutoRenewalsRouteImport.update({
  id: '/api/cron/auto-renewals',
  path: '/api/cron/auto-renewals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/qr-checkin': typeof QrCheckinRoute
  '/tv': typeof TvRoute
  '/audit-logs': typeof AuthedAuditLogsRoute
  '/backup': typeof AuthedBackupRoute
  '/branches': typeof AuthedBranchesRoute
  '/cash-register': typeof AuthedCashRegisterRoute
  '/check-ins': typeof AuthedCheckInsRoute
  '/classes': typeof AuthedClassesRoute
  '/corporate-accounts': typeof AuthedCorporateAccountsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/employee-attendance': typeof AuthedEmployeeAttendanceRoute
  '/employee-schedules': typeof AuthedEmployeeSchedulesRoute
  '/employee-vacations': typeof AuthedEmployeeVacationsRoute
  '/employees': typeof AuthedEmployeesRoute
  '/export': typeof AuthedExportRoute
  '/inventory': typeof AuthedInventoryRoute
  '/invoices': typeof AuthedInvoicesRoute
  '/members': typeof AuthedMembersRoute
  '/membership-freezes': typeof AuthedMembershipFreezesRoute
  '/membership-payments': typeof AuthedMembershipPaymentsRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/nutrition': typeof AuthedNutritionRoute
  '/packages': typeof AuthedPackagesRoute
  '/payroll': typeof AuthedPayrollRoute
  '/pos': typeof AuthedPosRoute
  '/product-categories': typeof AuthedProductCategoriesRoute
  '/products': typeof AuthedProductsRoute
  '/profile': typeof AuthedProfileRoute
  '/purchases': typeof AuthedPurchasesRoute
  '/qr-codes': typeof AuthedQrCodesRoute
  '/renewals': typeof AuthedRenewalsRoute
  '/reports': typeof AuthedReportsRoute
  '/sales': typeof AuthedSalesRoute
  '/settings': typeof AuthedSettingsRoute
  '/subscriptions': typeof AuthedSubscriptionsRoute
  '/suppliers': typeof AuthedSuppliersRoute
  '/trainers': typeof AuthedTrainersRoute
  '/users': typeof AuthedUsersRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/auto-renewals': typeof ApiCronAutoRenewalsRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/qr-checkin': typeof QrCheckinRoute
  '/tv': typeof TvRoute
  '/audit-logs': typeof AuthedAuditLogsRoute
  '/backup': typeof AuthedBackupRoute
  '/branches': typeof AuthedBranchesRoute
  '/cash-register': typeof AuthedCashRegisterRoute
  '/check-ins': typeof AuthedCheckInsRoute
  '/classes': typeof AuthedClassesRoute
  '/corporate-accounts': typeof AuthedCorporateAccountsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/employee-attendance': typeof AuthedEmployeeAttendanceRoute
  '/employee-schedules': typeof AuthedEmployeeSchedulesRoute
  '/employee-vacations': typeof AuthedEmployeeVacationsRoute
  '/employees': typeof AuthedEmployeesRoute
  '/export': typeof AuthedExportRoute
  '/inventory': typeof AuthedInventoryRoute
  '/invoices': typeof AuthedInvoicesRoute
  '/members': typeof AuthedMembersRoute
  '/membership-freezes': typeof AuthedMembershipFreezesRoute
  '/membership-payments': typeof AuthedMembershipPaymentsRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/nutrition': typeof AuthedNutritionRoute
  '/packages': typeof AuthedPackagesRoute
  '/payroll': typeof AuthedPayrollRoute
  '/pos': typeof AuthedPosRoute
  '/product-categories': typeof AuthedProductCategoriesRoute
  '/products': typeof AuthedProductsRoute
  '/profile': typeof AuthedProfileRoute
  '/purchases': typeof AuthedPurchasesRoute
  '/qr-codes': typeof AuthedQrCodesRoute
  '/renewals': typeof AuthedRenewalsRoute
  '/reports': typeof AuthedReportsRoute
  '/sales': typeof AuthedSalesRoute
  '/settings': typeof AuthedSettingsRoute
  '/subscriptions': typeof AuthedSubscriptionsRoute
  '/suppliers': typeof AuthedSuppliersRoute
  '/trainers': typeof AuthedTrainersRoute
  '/users': typeof AuthedUsersRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/auto-renewals': typeof ApiCronAutoRenewalsRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/qr-checkin': typeof QrCheckinRoute
  '/tv': typeof TvRoute
  '/_authed/audit-logs': typeof AuthedAuditLogsRoute
  '/_authed/backup': typeof AuthedBackupRoute
  '/_authed/branches': typeof AuthedBranchesRoute
  '/_authed/cash-register': typeof AuthedCashRegisterRoute
  '/_authed/check-ins': typeof AuthedCheckInsRoute
  '/_authed/classes': typeof AuthedClassesRoute
  '/_authed/corporate-accounts': typeof AuthedCorporateAccountsRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/employee-attendance': typeof AuthedEmployeeAttendanceRoute
  '/_authed/employee-schedules': typeof AuthedEmployeeSchedulesRoute
  '/_authed/employee-vacations': typeof AuthedEmployeeVacationsRoute
  '/_authed/employees': typeof AuthedEmployeesRoute
  '/_authed/export': typeof AuthedExportRoute
  '/_authed/inventory': typeof AuthedInventoryRoute
  '/_authed/invoices': typeof AuthedInvoicesRoute
  '/_authed/members': typeof AuthedMembersRoute
  '/_authed/membership-freezes': typeof AuthedMembershipFreezesRoute
  '/_authed/membership-payments': typeof AuthedMembershipPaymentsRoute
  '/_authed/notifications': typeof AuthedNotificationsRoute
  '/_authed/nutrition': typeof AuthedNutritionRoute
  '/_authed/packages': typeof AuthedPackagesRoute
  '/_authed/payroll': typeof AuthedPayrollRoute
  '/_authed/pos': typeof AuthedPosRoute
  '/_authed/product-categories': typeof AuthedProductCategoriesRoute
  '/_authed/products': typeof AuthedProductsRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/purchases': typeof AuthedPurchasesRoute
  '/_authed/qr-codes': typeof AuthedQrCodesRoute
  '/_authed/renewals': typeof AuthedRenewalsRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/sales': typeof AuthedSalesRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/subscriptions': typeof AuthedSubscriptionsRoute
  '/_authed/suppliers': typeof AuthedSuppliersRoute
  '/_authed/trainers': typeof AuthedTrainersRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/auto-renewals': typeof ApiCronAutoRenewalsRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/qr-checkin'
    | '/tv'
    | '/audit-logs'
    | '/backup'
    | '/branches'
    | '/cash-register'
    | '/check-ins'
    | '/classes'
    | '/corporate-accounts'
    | '/dashboard'
    | '/employee-attendance'
    | '/employee-schedules'
    | '/employee-vacations'
    | '/employees'
    | '/export'
    | '/inventory'
    | '/invoices'
    | '/members'
    | '/membership-freezes'
    | '/membership-payments'
    | '/notifications'
    | '/nutrition'
    | '/packages'
    | '/payroll'
    | '/pos'
    | '/product-categories'
    | '/products'
    | '/profile'
    | '/purchases'
    | '/qr-codes'
    | '/renewals'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/subscriptions'
    | '/suppliers'
    | '/trainers'
    | '/users'
    | '/admin/users'
    | '/api/auth/$'
    | '/api/cron/auto-renewals'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/qr-checkin'
    | '/tv'
    | '/audit-logs'
    | '/backup'
    | '/branches'
    | '/cash-register'
    | '/check-ins'
    | '/classes'
    | '/corporate-accounts'
    | '/dashboard'
    | '/employee-attendance'
    | '/employee-schedules'
    | '/employee-vacations'
    | '/employees'
    | '/export'
    | '/inventory'
    | '/invoices'
    | '/members'
    | '/membership-freezes'
    | '/membership-payments'
    | '/notifications'
    | '/nutrition'
    | '/packages'
    | '/payroll'
    | '/pos'
    | '/product-categories'
    | '/products'
    | '/profile'
    | '/purchases'
    | '/qr-codes'
    | '/renewals'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/subscriptions'
    | '/suppliers'
    | '/trainers'
    | '/users'
    | '/admin/users'
    | '/api/auth/$'
    | '/api/cron/auto-renewals'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/qr-checkin'
    | '/tv'
    | '/_authed/audit-logs'
    | '/_authed/backup'
    | '/_authed/branches'
    | '/_authed/cash-register'
    | '/_authed/check-ins'
    | '/_authed/classes'
    | '/_authed/corporate-accounts'
    | '/_authed/dashboard'
    | '/_authed/employee-attendance'
    | '/_authed/employee-schedules'
    | '/_authed/employee-vacations'
    | '/_authed/employees'
    | '/_authed/export'
    | '/_authed/inventory'
    | '/_authed/invoices'
    | '/_authed/members'
    | '/_authed/membership-freezes'
    | '/_authed/membership-payments'
    | '/_authed/notifications'
    | '/_authed/nutrition'
    | '/_authed/packages'
    | '/_authed/payroll'
    | '/_authed/pos'
    | '/_authed/product-categories'
    | '/_authed/products'
    | '/_authed/profile'
    | '/_authed/purchases'
    | '/_authed/qr-codes'
    | '/_authed/renewals'
    | '/_authed/reports'
    | '/_authed/sales'
    | '/_authed/settings'
    | '/_authed/subscriptions'
    | '/_authed/suppliers'
    | '/_authed/trainers'
    | '/_authed/users'
    | '/_authed/admin/users'
    | '/api/auth/$'
    | '/api/cron/auto-renewals'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  QrCheckinRoute: typeof QrCheckinRoute
  TvRoute: typeof TvRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronAutoRenewalsRoute: typeof ApiCronAutoRenewalsRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-checkin': {
      id: '/qr-checkin'
      path: '/qr-checkin'
      fullPath: '/qr-checkin'
      preLoaderRoute: typeof QrCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trainers': {
      id: '/_authed/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof AuthedTrainersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/suppliers': {
      id: '/_authed/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthedSuppliersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/subscriptions': {
      id: '/_authed/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthedSubscriptionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sales': {
      id: '/_authed/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthedSalesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/renewals': {
      id: '/_authed/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof AuthedRenewalsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/qr-codes': {
      id: '/_authed/qr-codes'
      path: '/qr-codes'
      fullPath: '/qr-codes'
      preLoaderRoute: typeof AuthedQrCodesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/purchases': {
      id: '/_authed/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthedPurchasesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products': {
      id: '/_authed/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthedProductsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/product-categories': {
      id: '/_authed/product-categories'
      path: '/product-categories'
      fullPath: '/product-categories'
      preLoaderRoute: typeof AuthedProductCategoriesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pos': {
      id: '/_authed/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthedPosRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/payroll': {
      id: '/_authed/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthedPayrollRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/packages': {
      id: '/_authed/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AuthedPackagesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/nutrition': {
      id: '/_authed/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthedNutritionRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notifications': {
      id: '/_authed/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedNotificationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/membership-payments': {
      id: '/_authed/membership-payments'
      path: '/membership-payments'
      fullPath: '/membership-payments'
      preLoaderRoute: typeof AuthedMembershipPaymentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/membership-freezes': {
      id: '/_authed/membership-freezes'
      path: '/membership-freezes'
      fullPath: '/membership-freezes'
      preLoaderRoute: typeof AuthedMembershipFreezesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/members': {
      id: '/_authed/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthedMembersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/invoices': {
      id: '/_authed/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthedInvoicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inventory': {
      id: '/_authed/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthedInventoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/export': {
      id: '/_authed/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthedExportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/employees': {
      id: '/_authed/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthedEmployeesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/employee-vacations': {
      id: '/_authed/employee-vacations'
      path: '/employee-vacations'
      fullPath: '/employee-vacations'
      preLoaderRoute: typeof AuthedEmployeeVacationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/employee-schedules': {
      id: '/_authed/employee-schedules'
      path: '/employee-schedules'
      fullPath: '/employee-schedules'
      preLoaderRoute: typeof AuthedEmployeeSchedulesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/employee-attendance': {
      id: '/_authed/employee-attendance'
      path: '/employee-attendance'
      fullPath: '/employee-attendance'
      preLoaderRoute: typeof AuthedEmployeeAttendanceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/corporate-accounts': {
      id: '/_authed/corporate-accounts'
      path: '/corporate-accounts'
      fullPath: '/corporate-accounts'
      preLoaderRoute: typeof AuthedCorporateAccountsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/classes': {
      id: '/_authed/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthedClassesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/check-ins': {
      id: '/_authed/check-ins'
      path: '/check-ins'
      fullPath: '/check-ins'
      preLoaderRoute: typeof AuthedCheckInsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cash-register': {
      id: '/_authed/cash-register'
      path: '/cash-register'
      fullPath: '/cash-register'
      preLoaderRoute: typeof AuthedCashRegisterRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/branches': {
      id: '/_authed/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthedBranchesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/backup': {
      id: '/_authed/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AuthedBackupRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit-logs': {
      id: '/_authed/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthedAuditLogsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/auto-renewals': {
      id: '/api/cron/auto-renewals'
      path: '/api/cron/auto-renewals'
      fullPath: '/api/cron/auto-renewals'
      preLoaderRoute: typeof ApiCronAutoRenewalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAuditLogsRoute: typeof AuthedAuditLogsRoute
  AuthedBackupRoute: typeof AuthedBackupRoute
  AuthedBranchesRoute: typeof AuthedBranchesRoute
  AuthedCashRegisterRoute: typeof AuthedCashRegisterRoute
  AuthedCheckInsRoute: typeof AuthedCheckInsRoute
  AuthedClassesRoute: typeof AuthedClassesRoute
  AuthedCorporateAccountsRoute: typeof AuthedCorporateAccountsRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedEmployeeAttendanceRoute: typeof AuthedEmployeeAttendanceRoute
  AuthedEmployeeSchedulesRoute: typeof AuthedEmployeeSchedulesRoute
  AuthedEmployeeVacationsRoute: typeof AuthedEmployeeVacationsRoute
  AuthedEmployeesRoute: typeof AuthedEmployeesRoute
  AuthedExportRoute: typeof AuthedExportRoute
  AuthedInventoryRoute: typeof AuthedInventoryRoute
  AuthedInvoicesRoute: typeof AuthedInvoicesRoute
  AuthedMembersRoute: typeof AuthedMembersRoute
  AuthedMembershipFreezesRoute: typeof AuthedMembershipFreezesRoute
  AuthedMembershipPaymentsRoute: typeof AuthedMembershipPaymentsRoute
  AuthedNotificationsRoute: typeof AuthedNotificationsRoute
  AuthedNutritionRoute: typeof AuthedNutritionRoute
  AuthedPackagesRoute: typeof AuthedPackagesRoute
  AuthedPayrollRoute: typeof AuthedPayrollRoute
  AuthedPosRoute: typeof AuthedPosRoute
  AuthedProductCategoriesRoute: typeof AuthedProductCategoriesRoute
  AuthedProductsRoute: typeof AuthedProductsRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedPurchasesRoute: typeof AuthedPurchasesRoute
  AuthedQrCodesRoute: typeof AuthedQrCodesRoute
  AuthedRenewalsRoute: typeof AuthedRenewalsRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedSalesRoute: typeof AuthedSalesRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedSubscriptionsRoute: typeof AuthedSubscriptionsRoute
  AuthedSuppliersRoute: typeof AuthedSuppliersRoute
  AuthedTrainersRoute: typeof AuthedTrainersRoute
  AuthedUsersRoute: typeof AuthedUsersRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAuditLogsRoute: AuthedAuditLogsRoute,
  AuthedBackupRoute: AuthedBackupRoute,
  AuthedBranchesRoute: AuthedBranchesRoute,
  AuthedCashRegisterRoute: AuthedCashRegisterRoute,
  AuthedCheckInsRoute: AuthedCheckInsRoute,
  AuthedClassesRoute: AuthedClassesRoute,
  AuthedCorporateAccountsRoute: AuthedCorporateAccountsRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedEmployeeAttendanceRoute: AuthedEmployeeAttendanceRoute,
  AuthedEmployeeSchedulesRoute: AuthedEmployeeSchedulesRoute,
  AuthedEmployeeVacationsRoute: AuthedEmployeeVacationsRoute,
  AuthedEmployeesRoute: AuthedEmployeesRoute,
  AuthedExportRoute: AuthedExportRoute,
  AuthedInventoryRoute: AuthedInventoryRoute,
  AuthedInvoicesRoute: AuthedInvoicesRoute,
  AuthedMembersRoute: AuthedMembersRoute,
  AuthedMembershipFreezesRoute: AuthedMembershipFreezesRoute,
  AuthedMembershipPaymentsRoute: AuthedMembershipPaymentsRoute,
  AuthedNotificationsRoute: AuthedNotificationsRoute,
  AuthedNutritionRoute: AuthedNutritionRoute,
  AuthedPackagesRoute: AuthedPackagesRoute,
  AuthedPayrollRoute: AuthedPayrollRoute,
  AuthedPosRoute: AuthedPosRoute,
  AuthedProductCategoriesRoute: AuthedProductCategoriesRoute,
  AuthedProductsRoute: AuthedProductsRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedPurchasesRoute: AuthedPurchasesRoute,
  AuthedQrCodesRoute: AuthedQrCodesRoute,
  AuthedRenewalsRoute: AuthedRenewalsRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedSalesRoute: AuthedSalesRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedSubscriptionsRoute: AuthedSubscriptionsRoute,
  AuthedSuppliersRoute: AuthedSuppliersRoute,
  AuthedTrainersRoute: AuthedTrainersRoute,
  AuthedUsersRoute: AuthedUsersRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  QrCheckinRoute: QrCheckinRoute,
  TvRoute: TvRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronAutoRenewalsRoute: ApiCronAutoRenewalsRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
